// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smgduxxzbfugpyonhmyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtZ2R1eHh6YmZ1Z3B5b25obXl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY1ODM0NzgsImV4cCI6MjA5MjE1OTQ3OH0.dwaPaJrVvQUrMzV9l4HnmSlvz0YzqBZgG7BqrPhT7S8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});